#!/usr/bin/env python
import subprocess

print "Checking repository for any file with lines greater than 80 chars"
listoffiles = subprocess.check_output(['git','ls-tree','--full-tree','--name-only','-r','HEAD'])
splitfiles = listoffiles.split('\n')
exitcode = 0
for thisfile in splitfiles:
    if not thisfile == '':
      print 'Checking file: ' + thisfile
      try:
        gitfile = open(thisfile,'r')
        gitlines = gitfile.readlines()
        for myline in gitlines:
          if(len(myline) > 80):
            print 'ERROR: Files must be limited to 80 characters per line! Check filename: ' + thisfile
            exit (1)
      except IOError:
        print "Can't open file for check, possibly deleted. Skipping: " + thisfile
print "Check line length script finished, allowing commit."
exit(0)

